blank_issues_enabled: false
contact_links:
  - name: âš ï¸ Extension/source issue
    url: https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose
    about: Issues and requests for extensions and sources should be opened in the tachiyomi-extensions repository instead
  - name: ğŸ“˜ Main Tachiyomi issue
    url: https://github.com/tachiyomiorg/tachiyomi/issues/new/choose
    about: Issues that exist on both this fork AND the original Tachiyomi should be opened in the tachiyomi repository instead
  - name: ğŸ“¦ Tachiyomi extensions
    url: https://tachiyomi.org/extensions
    about: List of all available extensions with download links
  - name: ğŸ–¥ï¸ Tachiyomi website
    url: https://tachiyomi.org/help/
    about: Guides, troubleshooting, and answers to common questions
